services:
  database:
    container_name: internship-database
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_internship_database
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'ConnectionStrings__InternshipDatabase=Host=database;Port=5432;Username=postgres;Password=postgres;Database=dev_internship_database'
    ports:
      - "8080:8080"
      - "8081:8081"
volumes:
  database-data: