/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanyFormRouteImport } from './routes/companyForm'
import { Route as ChangeDefaultPasswordRouteImport } from './routes/changeDefaultPassword'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountProfileIndexRouteImport } from './routes/account/profile/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyFormRoute = CompanyFormRouteImport.update({
  id: '/companyForm',
  path: '/companyForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeDefaultPasswordRoute = ChangeDefaultPasswordRouteImport.update({
  id: '/changeDefaultPassword',
  path: '/changeDefaultPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileIndexRoute = AccountProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/changeDefaultPassword': typeof ChangeDefaultPasswordRoute
  '/companyForm': typeof CompanyFormRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/register': typeof RegisterRoute
  '/account/': typeof AccountIndexRoute
  '/account/profile': typeof AccountProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changeDefaultPassword': typeof ChangeDefaultPasswordRoute
  '/companyForm': typeof CompanyFormRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/register': typeof RegisterRoute
  '/account': typeof AccountIndexRoute
  '/account/profile': typeof AccountProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/changeDefaultPassword': typeof ChangeDefaultPasswordRoute
  '/companyForm': typeof CompanyFormRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/register': typeof RegisterRoute
  '/account/': typeof AccountIndexRoute
  '/account/profile/': typeof AccountProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/changeDefaultPassword'
    | '/companyForm'
    | '/login'
    | '/management'
    | '/register'
    | '/account/'
    | '/account/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changeDefaultPassword'
    | '/companyForm'
    | '/login'
    | '/management'
    | '/register'
    | '/account'
    | '/account/profile'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/changeDefaultPassword'
    | '/companyForm'
    | '/login'
    | '/management'
    | '/register'
    | '/account/'
    | '/account/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  ChangeDefaultPasswordRoute: typeof ChangeDefaultPasswordRoute
  CompanyFormRoute: typeof CompanyFormRoute
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companyForm': {
      id: '/companyForm'
      path: '/companyForm'
      fullPath: '/companyForm'
      preLoaderRoute: typeof CompanyFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changeDefaultPassword': {
      id: '/changeDefaultPassword'
      path: '/changeDefaultPassword'
      fullPath: '/changeDefaultPassword'
      preLoaderRoute: typeof ChangeDefaultPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile/': {
      id: '/account/profile/'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountProfileIndexRoute: typeof AccountProfileIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountProfileIndexRoute: AccountProfileIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  ChangeDefaultPasswordRoute: ChangeDefaultPasswordRoute,
  CompanyFormRoute: CompanyFormRoute,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
