/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/sidebar'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangeDefaultPasswordRouteImport } from './routes/changeDefaultPassword'
import { Route as IndexRouteImport } from './routes/index'

const SidebarRoute = SidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeDefaultPasswordRoute = ChangeDefaultPasswordRouteImport.update({
  id: '/changeDefaultPassword',
  path: '/changeDefaultPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changeDefaultPassword': typeof ChangeDefaultPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sidebar': typeof SidebarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changeDefaultPassword': typeof ChangeDefaultPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sidebar': typeof SidebarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changeDefaultPassword': typeof ChangeDefaultPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sidebar': typeof SidebarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changeDefaultPassword'
    | '/login'
    | '/register'
    | '/sidebar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/changeDefaultPassword' | '/login' | '/register' | '/sidebar'
  id:
    | '__root__'
    | '/'
    | '/changeDefaultPassword'
    | '/login'
    | '/register'
    | '/sidebar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangeDefaultPasswordRoute: typeof ChangeDefaultPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SidebarRoute: typeof SidebarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changeDefaultPassword': {
      id: '/changeDefaultPassword'
      path: '/changeDefaultPassword'
      fullPath: '/changeDefaultPassword'
      preLoaderRoute: typeof ChangeDefaultPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangeDefaultPasswordRoute: ChangeDefaultPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SidebarRoute: SidebarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
